# Etapa de build
FROM node:18-alpine AS builder

WORKDIR /app

COPY bm-backend/package*.json ./
RUN npm install

COPY bm-backend/ .
RUN npm run build

# Etapa de producción
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./

EXPOSE 3000

CMD ["node", "dist/main"]
