version: "3.8"

services:
  bm-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: buscaminas-frontend
    ports:
      - "80:80"

  bm-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: buscaminas-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: buscaminas
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: buscaminas-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: buscaminas
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
