version: "3.8"

services:
  bm-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buscaminas-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
