version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: buscaminas-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 5Wd5AnHLe7RKMHR8gkPw
      POSTGRES_DB: buscaminas
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql

volumes:
  postgres_data:
