version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: buscaminas-mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./bm-backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
