service: buscaminas-backend

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: us-east-1
  stage: production
  memorySize: 2048
  timeout: 30
  environment:
    NODE_ENV: production
    PORT: 3001
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    DATABASE_URL: ${env:DATABASE_URL}  
    JWT_ACCESS_TOKEN_SECRET: ${env:JWT_ACCESS_TOKEN_SECRET}
    JWT_REFRESH_TOKEN_SECRET: ${env:JWT_REFRESH_TOKEN_SECRET}
    JWT_ACCESS_TOKEN_EXPIRATION_MS: ${env:JWT_ACCESS_TOKEN_EXPIRATION_MS}
    JWT_REFRESH_TOKEN_EXPIRATION_MS: ${env:JWT_REFRESH_TOKEN_EXPIRATION_MS}


functions:
  api:
    handler: dist/src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'


