service: buscaminas-backend

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: production
  region: us-east-1
  memorySize: 2048
  timeout: 30
  logRetentionInDays: 14

functions:
  api:
    handler: dist/src/lambda.handler
    layers:
      - arn:aws:lambda:us-east-1:864981737391:layer:prisma-layer:3
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-offline

package:
  patterns:
    - 'dist/**'
    - '!node_modules/@prisma/**'
    - '!node_modules/.prisma/**'
    - '!node_modules/aws-sdk/**'
    - '!node_modules/prisma/**'
    - '!node_modules/.cache/**'
    - '!node_modules/@swc/**'
    - '!**/*.map'
    - '!**/*.md'
    - '!**/test/**'
    - '!**/*.spec.ts'
    - '!**/.git/**'
    - '!**/.vscode/**'
    - '!scripts/**'
    - '!prisma/**'
    - '!**/.env*'

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    platform: 'node'
    concurrency: 10